//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DAL.SQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MM.DAL.SQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddressID.
        /// </summary>
        internal static string p_addressid {
            get {
                return ResourceManager.GetString("p_addressid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddressType.
        /// </summary>
        internal static string p_addresstype {
            get {
                return ResourceManager.GetString("p_addresstype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddressTypeID.
        /// </summary>
        internal static string p_addresstypeid {
            get {
                return ResourceManager.GetString("p_addresstypeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CityTown.
        /// </summary>
        internal static string p_citytown {
            get {
                return ResourceManager.GetString("p_citytown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Country.
        /// </summary>
        internal static string p_country {
            get {
                return ResourceManager.GetString("p_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Email.
        /// </summary>
        internal static string p_email {
            get {
                return ResourceManager.GetString("p_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FirstName.
        /// </summary>
        internal static string p_firstname {
            get {
                return ResourceManager.GetString("p_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LastName.
        /// </summary>
        internal static string p_lastname {
            get {
                return ResourceManager.GetString("p_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LineOne.
        /// </summary>
        internal static string p_lineone {
            get {
                return ResourceManager.GetString("p_lineone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LineThree.
        /// </summary>
        internal static string p_linethree {
            get {
                return ResourceManager.GetString("p_linethree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LineTwo.
        /// </summary>
        internal static string p_linetwo {
            get {
                return ResourceManager.GetString("p_linetwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MiddleName.
        /// </summary>
        internal static string p_middlename {
            get {
                return ResourceManager.GetString("p_middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Phone.
        /// </summary>
        internal static string p_phone {
            get {
                return ResourceManager.GetString("p_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PostalCode.
        /// </summary>
        internal static string p_postalcode {
            get {
                return ResourceManager.GetString("p_postalcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RenterID.
        /// </summary>
        internal static string p_renterid {
            get {
                return ResourceManager.GetString("p_renterid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @StateProvince.
        /// </summary>
        internal static string p_stateprovince {
            get {
                return ResourceManager.GetString("p_stateprovince", resourceCulture);
            }
        }
    }
}
