// <auto-generated />
namespace mmMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class startEndActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(startEndActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201301011855170_startEndActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
