// <auto-generated />
namespace mmMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userDetials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userDetials));
        
        string IMigrationMetadata.Id
        {
            get { return "201301011921535_userDetials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
