// <auto-generated />
namespace mmMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201301011829583_userProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
